=== phrase/strings-openapi/webhook_schemas/jobs_locale_complete.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "event": {
      "type": "string"
    },
    "message": {
      "type": "string"
    },
    "sent_at": {
      "type": "string",
      "format": "date-time"
    },
    "user": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "username": {
          "type": "string"
        },
        "name": {
          "type": [
            "string",
            "null"
          ]
        },
        "gravatar_uid": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "id",
        "username",
        "name",
        "gravatar_uid"
      ]
    },
    "project": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "main_format": {
          "type": [
            "string",
            "null"
          ]
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "updated_at": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "id",
        "name",
        "main_format",
        "created_at",
        "updated_at"
      ]
    },
    "branch": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "job": {
      "type": "object",
      "title": "job",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": [
            "string",
            "null"
          ]
        },
        "owner": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "username": {
              "type": "string"
            },
            "name": {
              "type": [
                "string",
                "null"
              ]
            }
          },
          "required": [
            "id",
            "username",
            "name"
          ]
        },
        "briefing": {
          "type": [
            "string",
            "null"
          ]
        },
        "due_date": {
          "type": [
            "string",
            "null"
          ],
          "format": "date-time"
        },
        "review_due_date": {
          "type": [
            "string",
            "null"
          ],
          "format": "date-time"
        },
        "state": {
          "type": [
            "string",
            "null"
          ]
        },
        "ticket_url": {
          "type": [
            "string",
            "null"
          ]
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "updated_at": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "id",
        "name",
        "owner",
        "briefing",
        "due_date",
        "state",
        "ticket_url",
        "created_at",
        "updated_at"
      ]
    },
    "locale": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "code": {
          "type": "string"
        },
        "default": {
          "type": "boolean"
        },
        "main": {
          "type": "boolean"
        },
        "rtl": {
          "type": "boolean"
        },
        "plural_forms": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "source_locale": {
          "type": [
            "object",
            "null"
          ],
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "code": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "name",
            "code"
          ]
        },
        "fallback_locale": {
          "type": [
            "object",
            "null"
          ],
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "code": {
              "type": "string"
            }
          },
          "required": [
            "id",
            "name",
            "code"
          ]
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "updated_at": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "id",
        "name",
        "code",
        "default",
        "main",
        "rtl",
        "plural_forms",
        "source_locale",
        "fallback_locale",
        "created_at",
        "updated_at"
      ]
    }
  },
  "required": [
    "event",
    "message",
    "user",
    "project",
    "job",
    "locale"
  ]
}

=== phrase/strings-openapi/webhook_schemas/jobs_locale_review_complete_example.json
{
  "event": "jobs:locale:review:complete",
  "message": "john.smith marked locale en of job Translation job for feature 1 in project Translation Project within branch new-feature-1 as reviewed",
  "sent_at": "2025-02-07 16:44:04 UTC",
  "user": {
    "id": "24b9a53ad72e198ca332fba91bb95f57",
    "username": "john.smith",
    "name": "John Smith",
    "gravatar_uid": "1bc5edb4799fd8eec67c66122f47eb73"
  },
  "project": {
    "id": "b2abd3bd2c23ff0ac546e0a2d9aa0be1",
    "name": "Translation Project",
    "slug": "translation-project",
    "main_format": "yml",
    "project_image_url": null,
    "created_at": "2025-02-07 16:18:13 UTC",
    "updated_at": "2025-02-07 16:18:13 UTC",
    "point_of_contact": null
  },
  "branch": {
    "name": "new-feature-1"
  },
  "locale": {
    "id": "7d8614f35033cebada71d4471fd87518",
    "name": "en",
    "code": "en",
    "default": false,
    "main": false,
    "rtl": false,
    "plural_forms": [
      "zero",
      "one",
      "other"
    ],
    "created_at": "2025-02-07 16:18:13 UTC",
    "updated_at": "2025-02-07 16:44:04 UTC",
    "source_locale": null,
    "fallback_locale": null
  },
  "job": {
    "id": "ad39faf87fb5af9aa9d9ab44a6c29899",
    "name": "Translation job for feature 1",
    "owner": {
      "id": "24b9a53ad72e198ca332fba91bb95f57",
      "username": "john.smith",
      "name": "John Smith"
    },
    "briefing": "Please translate everything!",
    "due_date": "2025-02-07 16:18:13 UTC",
    "review_due_date": null,
    "state": "draft",
    "ticket_url": "",
    "created_at": "2025-02-07 16:18:13 UTC",
    "updated_at": "2025-02-07 16:44:05 UTC"
  }
}
