=== phrase/strings-openapi/webhook_schemas/uploads_create.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "event": {
      "type": "string"
    },
    "message": {
      "type": "string"
    },
    "sent_at": {
      "type": "string",
      "format": "date-time"
    },
    "user": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "username": {
          "type": "string"
        },
        "name": {
          "type": [
            "string",
            "null"
          ]
        },
        "gravatar_uid": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "id",
        "username",
        "name",
        "gravatar_uid"
      ]
    },
    "project": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "main_format": {
          "type": [
            "string",
            "null"
          ]
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "updated_at": {
          "type": "string",
          "format": "date-time"
        }
      },
      "required": [
        "id",
        "name",
        "main_format",
        "created_at",
        "updated_at"
      ]
    },
    "branch": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "upload": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "filename": {
          "type": "string"
        },
        "format": {
          "type": "string"
        },
        "state": {
          "type": [
            "string",
            "null"
          ]
        },
        "tag": {
          "type": [
            "string",
            "null"
          ]
        },
        "tags": {
          "type": [
            "array"
          ],
          "items": {
            "type": "string"
          }
        },
        "summary": {
          "type": [
            "object",
            "null"
          ],
          "properties": {
            "locales_created": {
              "type": "integer"
            },
            "translation_keys_created": {
              "type": "integer"
            },
            "translation_keys_updated": {
              "type": "integer"
            },
            "translation_keys_unmentioned": {
              "type": "integer"
            },
            "translations_created": {
              "type": "integer"
            },
            "translations_updated": {
              "type": "integer"
            },
            "tags_created": {
              "type": "integer"
            },
            "translation_keys_ignored": {
              "type": "integer"
            }
          }
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "updated_at": {
          "type": "string",
          "format": "date-time"
        },
        "user": {
          "type": [
            "object",
            "null"
          ],
          "properties": {
            "id": {
              "type": "string"
            },
            "username": {
              "type": "string"
            },
            "name": {
              "type": [
                "string",
                "null"
              ]
            },
            "gravatar_uid": {
              "type": [
                "string",
                "null"
              ]
            }
          },
          "required": [
            "id",
            "username",
            "name",
            "gravatar_uid"
          ]
        }
      },
      "required": [
        "id",
        "filename",
        "format",
        "state",
        "tag",
        "summary",
        "created_at",
        "updated_at"
      ]
    }
  },
  "required": [
    "event",
    "message",
    "user",
    "project",
    "upload"
  ]
}

=== phrase/strings-openapi/webhook_schemas/uploads_processing_example.json
{
  "event": "uploads:processing",
  "message": "john.smith initialized file upload file.yml in project Translation Project within branch new-feature-1",
  "sent_at": "2025-02-07 16:44:04 UTC",
  "user": {
    "id": "24b9a53ad72e198ca332fba91bb95f57",
    "username": "john.smith",
    "name": "John Smith",
    "gravatar_uid": "1bc5edb4799fd8eec67c66122f47eb73"
  },
  "project": {
    "id": "b2abd3bd2c23ff0ac546e0a2d9aa0be1",
    "name": "Translation Project",
    "slug": "translation-project",
    "main_format": "yml",
    "project_image_url": null,
    "created_at": "2025-02-07 16:18:13 UTC",
    "updated_at": "2025-02-07 16:18:13 UTC",
    "point_of_contact": null
  },
  "branch": {
    "name": "new-feature-1"
  },
  "upload": {
    "id": "955ac73e72b75aae4fcaf2548798fe9c",
    "filename": "file.yml",
    "format": "yml",
    "state": "initialized",
    "created_at": "2025-02-07 16:18:13 UTC",
    "updated_at": "2025-02-07 16:18:13 UTC",
    "summary": {},
    "tag": null,
    "tags": [],
    "url": "http://www.example.com/accounts/company-account/projects/translation-project/uploads/955ac73e72b75aae4fcaf2548798fe9c?branch=new-feature-1",
    "user": {
      "id": "24b9a53ad72e198ca332fba91bb95f57",
      "username": "john.smith",
      "name": "John Smith",
      "gravatar_uid": "1bc5edb4799fd8eec67c66122f47eb73"
    }
  }
}
